/*
 * Copyright 2005-2009 StreamSpinner Project
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* Generated By:JavaCC: Do not edit this line. InnerParserConstants.java */
package org.streamspinner.harmonica.query.hamql;

public interface InnerParserConstants {

  int EOF = 0;
  int MASTER = 5;
  int SELECT = 6;
  int FROM = 7;
  int WHERE = 8;
  int AND = 9;
  int GROUP = 10;
  int BY = 11;
  int AS = 12;
  int NOW = 13;
  int UNION = 14;
  int ALL = 15;
  int TIME = 16;
  int CREATE = 17;
  int TABLE = 18;
  int INSERT = 19;
  int INTO = 20;
  int DROP = 21;
  int LONG = 22;
  int DOUBLE = 23;
  int STRING = 24;
  int OBJECT = 25;
  int LE = 26;
  int LT = 27;
  int GE = 28;
  int GT = 29;
  int EQ = 30;
  int NE = 31;
  int LK = 32;
  int RK = 33;
  int KLK = 34;
  int KRK = 35;
  int TLK = 36;
  int TRK = 37;
  int PLUS = 38;
  int MINUS = 39;
  int DIV = 40;
  int DOT = 41;
  int CONNMA = 42;
  int ASTER = 43;
  int SINGLE_QUOTATION = 44;
  int UNDERLINE = 45;
  int COLON = 46;
  int INTEGER_VALUE = 47;
  int DOUBLE_VALUE = 48;
  int NUMBER = 49;
  int LETTER = 50;
  int WORD = 51;
  int SPACE_WORD = 52;
  int WORDS = 53;
  int SPACE_DATE_WORD = 54;
  int DATE_WORDS = 55;
  int DATE_WORD = 56;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"MASTER\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"AND\"",
    "\"GROUP\"",
    "\"BY\"",
    "\"AS\"",
    "\"NOW\"",
    "\"UNION\"",
    "\"ALL\"",
    "\"TIME\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"DROP\"",
    "\"LONG\"",
    "\"DOUBLE\"",
    "\"STRING\"",
    "\"OBJECT\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"=\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\".\"",
    "\",\"",
    "\"*\"",
    "\"\\\'\"",
    "\"_\"",
    "\":\"",
    "<INTEGER_VALUE>",
    "<DOUBLE_VALUE>",
    "<NUMBER>",
    "<LETTER>",
    "<WORD>",
    "<SPACE_WORD>",
    "<WORDS>",
    "<SPACE_DATE_WORD>",
    "<DATE_WORDS>",
    "<DATE_WORD>",
  };

}
